apiVersion: apps/v1
kind: Deployment
metadata:
  name: mweather-go
  labels:
    app: mweather-go
    version: v1
spec:
  minReadySeconds: 1
  selector:
    matchLabels:
      app: mweather-go
      version: v1
  template:
    metadata:
      labels:
        app: mweather-go
        version: v1
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: mb-hangzhou
      containers:
      - imagePullPolicy: Always
        name: mweather-go
        image: mweather-go
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: port
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: user
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: pwd
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: host
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: port
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: pwd    
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: JAEGER_SERVICE_NAME
          value: $(APP_NAME).$(NAMESPACE) 
        - name: TRACING_AUTO_CREATE_SPAN
          value: "0"
        resources:
          requests:
            cpu: 20m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 500Mi
        ports:
        - containerPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: mweather-go
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mweather-go
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 90
---
apiVersion: v1
kind: Service
metadata:
  name: mweather-go
  labels:
    app: mweather-go
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: mweather-go