apiVersion: apps/v1
kind: Deployment
metadata:
  name: mweather-go
spec:
  template:
    spec:
      containers:
      - name: mweather-go
        env:
        - name: PROJECT_ENV
          value: "test"
        - name: MYSQL_DBNAME
          value: "mweather-go-test"          
